### ISSUE TITLE
About combining with pnm

### ISSUE THREAD

**Issue by julightzhong10** [zeke-xie/adaptive-inertia-adai#2]
Hi,

Firstly, thanks for the great work. 

I just wonder if adai is suitable for combining together with positive-negative momentum which is another work of you. From my understanding of these two, it is ok to replace the original momentum with pnm in adai. Do you have any suggestions or experiences?

Thanks for the reply.

**Comment by zeke-xie** [comment]
Hi julightzhong10,

Sorry for my late reply!
I did not notice this issue before.

I am not sure it is a good idea to combine Adai and Positive-Negative Momentum (PNM). 

And I do not know the theoretical convergence guarantee of the fusing variant of Adai + PNM.

In my mind, they have total different theoretical mechanisms.

However, I do think it is possible to combine Adai and Adam. Their adaptivity can co-work well.

Best wishes
